### ISSUE TITLE
Can't get Chat ID

### ISSUE THREAD

**Issue by iMoshi** [yrestom/erpnext_telegram#26]
Frappe v14.21.1
ERPNext v14.12.0
Erpnext Telegram Integration v1.1.0 (master)

Ubuntu 22.04.1 LTS x86_64
python telegram bot 20

I have followed your small tutorial on Discuss, and as soon I press Get Chat ID I get 

`Failed to load resource: 500 error: https://mysite/api/method/erpnext_telegram_integration.erpnext_telegram_integration.doctype.telegram_user_settings.telegram_user_settings.get_chat_id_button`

I've installed python telegram bot in my bench env, as well outside my bench env.

**Comment by iMoshi** [comment]
Just noticed, I'm also getting `GET https://mysite/assets/js/erpnext_telegram_integration.min.js net::ERR_ABORTED 404 (Not Found)`

**Comment by iMoshi** [comment]
My Traceback is:

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
TypeError: get_chat_id_button() missing 2 required positional arguments: 'telegram_token' and 'telegram_settings'`

**Comment by dineshpanchal93** [comment]
Same error i also facing !!! In version 14

**Comment by iMoshi** [comment]
Thank you! All good now :)
