### ISSUE TITLE
async with bot: AttributeError: __aenter__

### ISSUE THREAD

**Issue by Govind-Jangid** [yrestom/erpnext_telegram#36]
request.js:457
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/erpnext_telegram_integration/erpnext_telegram_integration/erpnext_telegram_integration/doctype/telegram_user_settings/telegram_user_settings.py", line 52, in get_chat_id_button
    chat_id = asyncio.run(get_chat_id(telegram_token_bot, telegram_token))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "apps/erpnext_telegram_integration/erpnext_telegram_integration/erpnext_telegram_integration/doctype/telegram_user_settings/telegram_user_settings.py", line 60, in get_chat_id
    async with bot:
AttributeError: __aenter__

**Frappe Framework - v14.41.0
ERPNext - v14.31.3**

**Comment by nilpatel42** [comment]
how to solve this error, when i click on GET ID, error popups 

![image](https://github.com/yrestom/erpnext_telegram/assets/135511086/2e5183c6-9b93-4ab1-a7d3-5fe5b753f903)

thank you
